### ISSUE TITLE
Revise the information architecture (organization) of the www.facebase.org site

### ISSUE THREAD

**Issue by robes** [facebase-org/site#12]
We need to revise the organization of the facebase.org site to support the various content produced by spokes. For instance, the fish face content, facial norms calculator and content, gene summary content, etc. and new data that is being produced for the site. These data may not be the typical data zip files that one searches for and downloads in the 'data browser' but are still valuable information for the community. Then we need to define standards for the data that spokes produce, including technical details of what they are allowed to produce for the site (e.g., is php allowed, is html allowed, is jekyl only allowed?).

Subtasks:
- [ ] revised information architecture for the site
- [ ] update content to reflect new architecture
- [ ] define new standards for spokes
- [ ] define policy and process for accepting 'web content' types of submissions from spokes

**Comment by crisaless** [comment]
moving to the facebase-project repo
