### ISSUE TITLE
Home/Landing page links to data browser

### ISSUE THREAD

**Issue by robes** [facebase-org/site#3]
We need to enhancement from 
- informatics-isi-edu/chaise#1

Then we need updates to the facebase landing page to link to mouse, human, zebrafish, microct, etc.

**Comment by crisaless** [comment]
This is more than just the links - it's a redesign of the home page.
Here's the first iteration.
![facebase-home-v2](https://cloud.githubusercontent.com/assets/8965132/9772925/ffb6d3b2-56f3-11e5-8514-cef53ee153c6.png)

**Comment by robes** [comment]
It looks good. Couple thoughts:
- would it be worth trying out a different color for the top menu bar, something more subtle like maybe the same dark blue used in some of the boxes at the bottom of the page?
- since the menu bar runs the full length of the page but the content is fixed to a narrower width of the page, would it be good to provide a border or page outline or background (very light gray etc) around the non content area?

**Comment by crisaless** [comment]
Sounds good. It'll add that in the next pass.

**Comment by crisaless** [comment]
This is related to Division issue #7 https://github.com/informatics-isi-edu/division/issues/7

**Comment by crisaless** [comment]
moving to facebase-project repo
